import Head from 'next/head'
import { Home } from "../containers/Home";
import { airdrops } from '../airdrops';
import { Airdrop } from "../types/Airdrop";
import { useEffect } from "react";
import { Text, Center } from '@chakra-ui/react'

interface HomePageprops {
  airdrops: Airdrop[]
}

export default function HomePage({ airdrops }: HomePageprops) { // run in client 

  useEffect(() => {
    console.log("airdrops", airdrops)
  }, [])

  return (
    <div >
      <Head>
        <title>Geostream Airdrop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Center>
          <Text
            fontSize='4xl'
            bgGradient='linear(to-l, #7928CA, #FF0080)'
            bgClip='text'
            as='b'
          >
            NFT Location Airdrop</Text>
        </Center>
        <Center>
          <Text
            fontSize='xl'
            mb={12}
            as='i'
          >check out all the available airdrops</Text>
        </Center>

        <div>
          <Home airdrops={airdrops} />
        </div>
      </main>
    </div>
  )
}

export function getStaticProps() { // run server side 
  return {
    props: {
      airdrops
    }
  }
}
