import Head from 'next/head'
import { Home } from "../containers/Home";
import { airdrops } from '../airdrops';
import { Airdrop } from "../types/Airdrop";
import { useEffect, useState } from "react";
import { Text, Center } from '@chakra-ui/react'
import { useContractReads, useContractRead } from 'wagmi'
import { LogicContractAddress } from "../config/addresses"
import LogicContract from "../artifacts/contracts/Logic.sol/Logic.json"

interface HomePageprops {
  airdrops: Airdrop[]
}

export default function HomePage({ airdrops }: HomePageprops) { // run in client 

  const logicContract = {
    address: LogicContractAddress,
    abi: LogicContract.abi,
  }

  const { data: airdropHashes } = useContractRead({
    address: logicContract.address,
    abi: logicContract.abi,
    functionName: "getAllHashes",
    chainId: 4690,
    onSuccess: (data) => console.log("data", data)
  })

  return (
    <div >
      <Head>
        <title>Geostream Airdrop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Center>
          <Text
            fontSize='4xl'
            bgGradient='linear(to-l, #7928CA, #FF0080)'
            bgClip='text'
            as='b'
          >
            NFT GeoStream Airdrop</Text>
        </Center>
        <Center>
          <Text
            fontSize='xl'
            as='i'
          >check out all the available airdrops</Text>
        </Center>

        <div>
          <Home airdropsHashes={airdropHashes || []} />
        </div>
      </main>
    </div>
  )
}

export function getStaticProps() { // run server side 
  return {
    props: {
      airdrops
    }
  }
}
