import Head from 'next/head'
import { Home } from "../containers/Home";
import { airdrops } from '../airdrops';
import { Airdrop } from "../types/Airdrop";
import { useEffect } from "react";
import { Text, Center } from '@chakra-ui/react'
import { useContractReads } from 'wagmi'
import { LogicContractAddress } from "../config/addresses"
import LogicContract from "../artifacts/contracts/Logic.sol/Logic.json"

interface HomePageprops {
  airdrops: Airdrop[]
}

export default function HomePage({ airdrops }: HomePageprops) { // run in client 

  const logicContract = {
    address: LogicContractAddress,
    abi: LogicContract.abi,
  }

  const { data: airdropHashes } = useContractReads({
   
    contracts: [
      {
        ...logicContract,
        functionName: "getAllHashes",
        chainId: 4690,
      }
    ]
  })

  const hashes = airdropHashes?.[0];

  useEffect(() => {
    console.log("hashes", hashes)
  }, [])

  return (
    <div >
      <Head>
        <title>Geostream Airdrop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Center>
          <Text
            fontSize='4xl'
            bgGradient='linear(to-l, #7928CA, #FF0080)'
            bgClip='text'
            as='b'
          >
            NFT Location Airdrop</Text>
        </Center>
        <Center>
          <Text
            fontSize='xl'
            mb={12}
            as='i'
          >check out all the available airdrops</Text>
        </Center>

        <div>
          <Home airdrops={airdrops} />
        </div>
      </main>
    </div>
  )
}

export function getStaticProps() { // run server side 
  return {
    props: {
      airdrops
    }
  }
}
